### ISSUE TITLE
gitlab osv-scanner

### ISSUE THREAD

**Issue by jsqfengbao** [google/osv-scanner-action#33]
If I want to use osv-scanner on gitlab, how do I configure the yml file? Is there a corresponding tool or plug-in that can be installed?

**Comment by oliverchang** [comment]
We currently don't have support for GitLab unfortunately, but we'd be very happy to take contributions!

**Comment by jsqfengbao** [comment]
> We currently don't have support for GitLab unfortunately, but we'd be very happy to take contributions!

OK, I'd love to

**Comment by andrewpollock** [comment]
https://docs.gitlab.com/ee/ci/migration/github_actions.html is probably relevant...

**Comment by andrewpollock** [comment]
Also https://about.gitlab.com/blog/2024/02/27/how-to-integrate-custom-security-scanners-into-gitlab/#tutorial-integrating-custom-security-scanners as surfaced in https://groups.google.com/g/osv-discuss/c/1zA5yRWJK9w

**Comment by H4x0rcr4x** [comment]
> Also https://about.gitlab.com/blog/2024/02/27/how-to-integrate-custom-security-scanners-into-gitlab/#tutorial-integrating-custom-security-scanners as surfaced in https://groups.google.com/g/osv-discuss/c/1zA5yRWJK9w

Adding to this:

Integrating a security scanner, with results automatically presented in various places in GitLab, means ensuring the output is in a [GitLab-specified format](https://docs.gitlab.com/ee/development/integrations/secure.html#report).
 
[Integrating external security scanners into your DevSecOps workflow](https://about.gitlab.com/blog/2024/04/08/integrate-external-security-scanners-into-your-devsecops-workflow/) blog post provides an example of using a custom Synk and a script to convert the resulting JSON to the [GitLab-specified format](https://docs.gitlab.com/ee/development/integrations/secure.html#report).
 
You can find the schemas for existing scanners here: 
 
[Container Scanning](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/container-scanning-report-format.json)
[Coverage Fuzzing](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/coverage-fuzzing-report-format.json)
[DAST](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/dast-report-format.json)
[Dependency Scanning](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/dependency-scanning-report-format.json) (this is likely the one that you will want to use for OSV-Scanner)
[SAST](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/sast-report-format.json)
[Secret Detection](https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/secret-detection-report-format.json)
 
Your output will need to adhere to one of these schemas. The docs provide further details on the available [Report Fields](https://docs.gitlab.com/ee/development/integrations/secure.html#report-fields) in these schemas.

**Comment by H4x0rcr4x** [comment]
Currently, you can run OSV-Scanner in GitLab by adding something similar to your **.gitlab-ci.yml** file. Ensure that you reference the latest stable image, which is currently version 1.9.1.

![Image](https://github.com/user-attachments/assets/27b8209a-cfaf-41a0-8008-6cdc4b4a7559)

**Comment by H4x0rcr4x** [comment]
Let me know who I can send a boatload of ☕️🧋to for your help with making this a reality! 
Thank you!!!

**Comment by H4x0rcr4x** [comment]
> If I want to use osv-scanner on gitlab, how do I configure the yml file? Is there a corresponding tool or plug-in that can be installed?

I just posted how to do it in GitLab. I have had **osv-scanner** running in GitLab for a few months.

**Comment by cuixq** [comment]
Thank you @H4x0rcr4x for sharing the configuration file!

**Comment by H4x0rcr4x** [comment]
Here is the updated configuration to enable **osv-scanner** in GitLab's .**gitlab-ci.yml** file.

```
#
# common
# OSV scanner for vulnerabilities
# This matches the OSV scanner in spark-app
#
osv_scanner:
  stage: test
  rules: 
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  
  image:
    name: ghcr.io/google/osv-scanner:v1.9.1 # osv-scanner final v1 stable image
    entrypoint: [""] # Override entry point
  script: # osv-scanner recursively scans the project for dependencies
    - /osv-scanner --format json --call-analysis -r . > osv-scanner-report.json
  artifacts:
    paths:
      - osv-scanner-report.json
    expire_in: 7 days
```
