### ISSUE TITLE
launch in different variants

### ISSUE THREAD

**Issue by pfi79** [google/osv-scanner-action#66]
How do I configure a different (not main or master) branch to run on a schedule?

How do I schedule a separate tag to run?

**Comment by another-rex** [comment]
I think this is more of a github workflow question, which I think is best answered with a combination of our docs here:

https://google.github.io/osv-scanner/github-action/

and Github's workflow trigger docs:

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow

Let me know if this helps!

**Comment by pfi79** [comment]
Let me try to describe my problem.
I have LTS versions that I want to keep up to date. They are in 2 brunches: main and another-branch. Also, each of the brunches has the latest tags exposed, which may be lagging behind the last commit. I would like to check on a schedule to see if all these 4 entities have gone bad.

Let's consider your proposed use case for scheduled:

```
name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: "30 12 * * 1"

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-scheduled:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.0"
```

What will unload to test such a variant? As it seems to me, only the default brunch (in my case it's main), last comit. And how to check other variants by schedule?

**Comment by pfi79** [comment]
I tried something like this:

```
jobs:
  latest:
    runs-on:  ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - another-branch
    steps:
      - name: Checkout ${{ matrix.ref }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Scan
        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.0"
```

I'm getting an error:

```
reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps
```

 I then went into your [file](https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable.yml#L64) and found that whatever I did would have no effect whatsoever. unloaded the default brunch, last comit, for verification purposes

**Comment by pfi79** [comment]
As I think you need to add the `ref: ‘’` parameter.

and in case of a scheduled run, change the unloading section 

```
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ inputs.checkout-ref }}
          submodules: ${{ inputs.checkout-submodules }}
```
