### ISSUE TITLE
configuration not found warning when using unified gh workflow

### ISSUE THREAD

**Issue by shahar-h** [google/osv-scanner-action#7]
I'm using the unified osv-scanner gh workflow in my repo:

```yaml
name: OSV-Scanner

on:
  pull_request:
    branches:
    - "main"
  merge_group:
    branches:
    - "main"
  push:
    branches:
    - "main"
  schedule:
  - cron: '44 15 * * 5'

permissions:
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"  # v1.7.1
    permissions:
      contents: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@1f1242919d8a60496dd1874b24b62b2370ed4c78"  # v1.7.1
    permissions:
      contents: read
      # Require writing security events to upload SARIF file to security tab
      security-events: write
```

I get the following warning on PRs:
<img width="817" alt="image" src="https://github.com/google/osv-scanner-action/assets/16555289/a7de92c3-00fe-4423-8dd9-c1ecb6e0bbda">

I guess that it's related to the fact that the job name is different between reusable workflows:
* [osv-scanner-reusable.yml](https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable.yml) - `osv-scan`
* [osv-scanner-reusable-pr.yml](https://github.com/google/osv-scanner-action/blob/main/.github/workflows/osv-scanner-reusable-pr.yml) - `scan-pr`

Can you assist?
